// 家族语言标准（2026-10-04 定案，随 Pic2WebP）：en / zh / ja / ko / de / es / pt / ar 共 8 语。
// 许可文案逐键对齐 Pic2WebP i18n.js（4f669ac 起），家族术语保持一致。
// 选择记在本机（rocktier.lang），不改系统设置；无偏好时默认英文，不嗅探系统语言。
const STRINGS = {
  zh: {
    title: "Rocktier OCR",
    tagline: "扫描件变可搜索",
    dropBig: "把 PDF 或图片拖到这里",
    dropSub1: "扫描件与图片型 PDF 会被识别，并加上可搜索的文字层",
    dropSub2: "图片会被包成一页可搜索的 PDF；原生电子版整页跳过，一个字符都不动",
    imageDone: (s) =>
      `已把这张图包成 <b>一页可搜索的 PDF</b>，识别出 ${s.lines} 行文本。`,
    start: "开始转换",
    exportPdf: "导出 PDF",
    cancel: "取消",
    exportTxt: "导出 TXT",
    copyText: "复制文本",
    copied: (n) => `已复制 ${n} 字符到剪贴板。`,
    exportDone: (s) => `已导出 TXT：${s.pages} 页、${s.lines} 行、${s.chars} 字符。`,
    txtName: "文本",
    pdfName: "PDF 文档",
    converted: (s) =>
      `转换完成：<b>${s.pages_total} 页</b>（识别 ${s.pages_ocr} 页、原生跳过 ${s.pages_skipped} 页），${s.lines} 行。`,
    pdfDone: (r) => `已导出可搜索 PDF：<b>${r.pages} 页</b>。`,
    copyFailed: "复制失败：",
    exportFailed: "导出失败：",
    preparing: "准备中…",
    statusPage: (p, t, phase) => `页 ${p}/${t} · ${phase}`,
    done: (s) =>
      `完成：<b>${s.pages_ocr} 页</b>识别加层，${s.pages_skipped} 页原生跳过，共 ${s.lines} 行文本。`,
    already:
      "这份 PDF 本来就可搜索 —— 每一页都已带有文字层（通常是 Word/Excel 导出的），没有需要识别的像素，所以原样保留，一个字符都没有动。",
    alreadyLog: "该文档已含文字层，无需识别。",
    output: "输出",
    finished: "完成 ✅ 输出：",
    cancelled: "已取消。",
    failed: "失败：",
    statusCancelled: "已取消",
    statusFailed: "失败",
    statusDone: "完成",
    footer: "识别在本机完成，文档不会离开这台电脑。",
    dialogFailed: "打开文件对话框失败：",
    saveDialogFailed: "打开保存对话框失败：",
    notFile: "拖入的不是文件，或系统未提供路径。",
    dragNotEnabled: "拖拽监听未启用：",
    startLog: "开始处理：",
    saveDefault: "-searchable",
    themeToLight: "切换到浅色",
    themeToDark: "切换到深色",
    themeLabel: "主题",
    themeModeAuto: "跟随系统",
    themeModeLight: "浅色",
    themeModeDark: "深色",
    license: {
      title: "许可与激活",
      loading: "正在检查…",
      trialLeft: (d) => `免费试用中 —— 还剩 ${d} 天。`,
      trialChip: (d) => `试用 · ${d} 天`,
      expiredChip: "未激活",
      expired: "试用已结束。识别仍可用；导出 PDF/TXT 需要激活。",
      licensed: "已激活。谢谢。",
      licensedFamily: "已激活 —— 全家桶，所有 Rocktier 应用均已解锁。",
      licensedNote: "此副本已激活。此后不再有任何校验，也不联网。",
      storeNote: "此副本购自微软商店，许可由商店负责。",
      notConfigured: "此构建尚未配置验签公钥，暂时无法激活。请写信到 hello@rocktier.com。",
      codeLabel: "激活码",
      codePlaceholder: "RKT-…",
      activate: "激活",
      activating: "正在激活…",
      buy: "购买 — $14.99",
      close: "关闭",
      invalid: "该激活码未被接受。请检查是否输错（不区分大小写）。",
      wrongProduct: "这个激活码属于另一个 Rocktier 应用。每个应用各有自己的码，或者用全家桶（可解锁全部）。",
      refunded: "这个激活码对应的购买已退款，因此不能再解锁。如属误判，请把订单号发到 hello@rocktier.com。",
      offline: "连不上 rocktier.com。激活需要一次联网，之后便不再联网。",
      whereToFind: "付款后页面上会显示激活码，购买确认邮件里也有一份。",
      privacyNote: "激活会把激活码发送到 rocktier.com 一次，并把签名回执保存在本机。除此之外不传输任何内容。",
      exportHintTrial: (d) => `导出 PDF/TXT 需要授权 —— 试用还剩 ${d} 天。`,
      exportHintExpired: "试用已结束，导出 PDF/TXT 需要先激活。",
    },
  },
  en: {
    title: "Rocktier OCR",
    tagline: "Make scans searchable",
    dropBig: "Drop a PDF or an image here",
    dropSub1: "Scans and image-only PDFs are recognised and given a searchable text layer",
    dropSub2: "An image is wrapped into a one-page searchable PDF; born-digital pages are skipped untouched",
    imageDone: (s) =>
      `Wrapped the image into <b>a one-page searchable PDF</b> with ${s.lines} lines of text.`,
    start: "Convert",
    exportPdf: "Export PDF",
    cancel: "Cancel",
    exportTxt: "Export TXT",
    copyText: "Copy text",
    copied: (n) => `Copied ${n} characters to the clipboard.`,
    exportDone: (s) => `TXT exported: ${s.pages} page(s), ${s.lines} lines, ${s.chars} characters.`,
    txtName: "Text",
    pdfName: "PDF document",
    converted: (s) =>
      `Converted: <b>${s.pages_total} page(s)</b> - ${s.pages_ocr} recognised, ${s.pages_skipped} already readable, ${s.lines} lines.`,
    pdfDone: (r) => `Searchable PDF exported: <b>${r.pages} page(s)</b>.`,
    copyFailed: "Copy failed: ",
    exportFailed: "Export failed: ",
    preparing: "Preparing…",
    statusPage: (p, t, phase) => `Page ${p}/${t} · ${phase}`,
    done: (s) =>
      `Done: <b>${s.pages_ocr} page(s)</b> recognised and layered, ${s.pages_skipped} skipped, ${s.lines} lines of text.`,
    already:
      "This PDF is already searchable — every page carries its own text layer (typically exported from Word or Excel). There are no pixels to recognise, so nothing was changed.",
    alreadyLog: "The document already has a text layer; no recognition needed.",
    output: "Output",
    finished: "Done ✅ output: ",
    cancelled: "Cancelled.",
    failed: "Failed: ",
    statusCancelled: "Cancelled",
    statusFailed: "Failed",
    statusDone: "Done",
    footer: "Recognition happens on this machine. Your document never leaves it.",
    dialogFailed: "Could not open the file dialog: ",
    saveDialogFailed: "Could not open the save dialog: ",
    notFile: "That drop was not a file, or the system gave no path.",
    dragNotEnabled: "Drag-and-drop listener unavailable: ",
    startLog: "Processing: ",
    saveDefault: "-searchable",
    themeToLight: "Switch to light",
    themeToDark: "Switch to dark",
    themeLabel: "Theme",
    themeModeAuto: "Follow system",
    themeModeLight: "Light",
    themeModeDark: "Dark",
    license: {
      title: "License",
      loading: "Checking…",
      trialLeft: (d) => `Free trial — ${d} day(s) left.`,
      trialChip: (d) => `Trial · ${d}d`,
      expiredChip: "Not activated",
      expired: "Your trial has ended. Recognition still works; exporting PDF/TXT needs a license.",
      licensed: "Licensed. Thank you.",
      licensedFamily: "Licensed — family bundle. Every Rocktier app is unlocked.",
      licensedNote: "This copy is activated. No further checks, and no network access.",
      storeNote: "This copy came from the Microsoft Store, so the Store handles the license for it.",
      notConfigured: "This build cannot activate a code yet — it carries no verification key. Please write to hello@rocktier.com.",
      codeLabel: "Activation code",
      codePlaceholder: "RKT-…",
      activate: "Activate",
      activating: "Activating…",
      buy: "Buy — $14.99",
      close: "Close",
      invalid: "That code was not accepted. Check it for a typo — the code is not case-sensitive.",
      wrongProduct: "That code belongs to a different Rocktier app. Each app has its own code — or the family bundle, which unlocks all of them.",
      refunded: "That code was refunded, so it no longer unlocks anything. If this is a mistake, write to hello@rocktier.com with your order number.",
      offline: "Could not reach rocktier.com. Activating needs one connection; after that the app stays offline.",
      whereToFind: "Your code was shown on the page right after payment, and is in the purchase email too.",
      privacyNote: "Activating sends the code to rocktier.com once and stores the signed reply locally. Nothing else is sent.",
      exportHintTrial: (d) => `Exporting PDF/TXT needs a license — ${d} day(s) left in your trial.`,
      exportHintExpired: "Your trial has ended — activate to export PDF/TXT.",
    },
  },
  ja: {
    title: "Rocktier OCR",
    tagline: "スキャンを検索可能に",
    dropBig: "PDF または画像をここにドロップ",
    dropSub1: "スキャン画像と画像のみの PDF は認識され、検索可能なテキスト層が付きます",
    dropSub2: "画像は 1 ページの検索可能な PDF に変換。デジタル由来のページは 1 文字も触れずにスキップ",
    imageDone: (s) =>
      `この画像を <b>1 ページの検索可能な PDF</b> に変換しました。${s.lines} 行のテキストを認識。`,
    start: "変換を開始",
    exportPdf: "PDF を書き出す",
    cancel: "キャンセル",
    exportTxt: "TXT を書き出す",
    copyText: "テキストをコピー",
    copied: (n) => `${n} 文字をクリップボードにコピーしました。`,
    exportDone: (s) => `TXT を書き出しました：${s.pages} ページ、${s.lines} 行、${s.chars} 文字。`,
    txtName: "テキスト",
    pdfName: "PDF ドキュメント",
    converted: (s) =>
      `変換完了：<b>${s.pages_total} ページ</b>（認識 ${s.pages_ocr} ページ、スキップ ${s.pages_skipped} ページ）、${s.lines} 行。`,
    pdfDone: (r) => `検索可能な PDF を書き出しました：<b>${r.pages} ページ</b>。`,
    copyFailed: "コピーに失敗：",
    exportFailed: "書き出しに失敗：",
    preparing: "準備中…",
    statusPage: (p, t, phase) => `ページ ${p}/${t} · ${phase}`,
    done: (s) =>
      `完了：<b>${s.pages_ocr} ページ</b>を認識して層を追加、${s.pages_skipped} ページをスキップ、合計 ${s.lines} 行。`,
    already:
      "この PDF はすでに検索可能です — すべてのページにテキスト層があります（Word/Excel の書き出しに多い）。認識すべきピクセルがないため、1 文字も変えずにそのまま保ちます。",
    alreadyLog: "この文書には既にテキスト層があるため、認識は不要です。",
    output: "出力",
    finished: "完了 ✅ 出力：",
    cancelled: "キャンセルしました。",
    failed: "失敗：",
    statusCancelled: "キャンセル",
    statusFailed: "失敗",
    statusDone: "完了",
    footer: "認識はこのマシン上で行われます。文書が外へ出ることはありません。",
    dialogFailed: "ファイルダイアログを開けませんでした：",
    saveDialogFailed: "保存ダイアログを開けませんでした：",
    notFile: "ドロップされたのはファイルではないか、システムがパスを返しませんでした。",
    dragNotEnabled: "ドラッグ＆ドロップのリスナーが無効です：",
    startLog: "処理を開始：",
    saveDefault: "-searchable",
    themeToLight: "ライトへ切替",
    themeToDark: "ダークへ切替",
    themeLabel: "テーマ",
    themeModeAuto: "システムに従う",
    themeModeLight: "ライト",
    themeModeDark: "ダーク",
    license: {
      title: "ライセンス認証",
      loading: "確認中…",
      trialLeft: (d) => `無料トライアル中 — 残り ${d} 日。`,
      trialChip: (d) => `トライアル · ${d}日`,
      expiredChip: "未認証",
      expired: "トライアルは終了しました。認識は引き続き利用でき、PDF/TXT の書き出しにはライセンスが必要です。",
      licensed: "ライセンス済み。ありがとうございます。",
      licensedFamily: "ライセンス済み — ファミリーバンドル。すべての Rocktier アプリが使えます。",
      licensedNote: "このコピーは認証済みです。以降の検査もネットワーク接続も行いません。",
      storeNote: "このコピーは Microsoft Store で購入されたもので、ライセンスはストアが管理します。",
      notConfigured: "このビルドには検証鍵が含まれておらず、現在コードで認証できません。hello@rocktier.com までご連絡ください。",
      codeLabel: "認証コード",
      codePlaceholder: "RKT-…",
      activate: "認証",
      activating: "認証中…",
      buy: "購入 — $14.99",
      close: "閉じる",
      invalid: "この認証コードは受け付けられませんでした。入力ミスがないかご確認ください（大文字小文字は区別されません）。",
      wrongProduct: "この認証コードは別の Rocktier アプリ用です。アプリごとに専用のコードがあります。すべて使えるファミリーバンドルもあります。",
      refunded: "この認証コードは返金された購入に紐づいているため、利用できません。誤りだと思われる場合は、注文番号を添えて hello@rocktier.com までご連絡ください。",
      offline: "rocktier.com に接続できません。認証には一度だけネット接続が必要で、以降はオフラインで動作します。",
      whereToFind: "コードは購入直後にページに表示され、購入確認メールにも記載されています。",
      privacyNote: "認証時にはコードが一度だけ rocktier.com に送信され、署名された応答がローカルに保存されます。それ以外の情報は送信されません。",
      exportHintTrial: (d) => `PDF/TXT の書き出しにはライセンスが必要です — トライアル残り ${d} 日。`,
      exportHintExpired: "トライアルは終了しました — 書き出すには先に認証してください。",
    },
  },
  ko: {
    title: "Rocktier OCR",
    tagline: "스캔본을 검색 가능하게",
    dropBig: "PDF나 이미지를 여기에 놓으세요",
    dropSub1: "스캔본과 이미지 전용 PDF는 인식하여 검색 가능한 텍스트 레이어를 붙입니다",
    dropSub2: "이미지는 한 페이지짜리 검색 가능한 PDF로 감싸고, 디지털 원본 페이지는 한 글자도 건드리지 않고 건너뜁니다",
    imageDone: (s) =>
      `이 이미지를 <b>한 페이지짜리 검색 가능한 PDF</b>로 만들었습니다. ${s.lines}줄의 텍스트를 인식했습니다.`,
    start: "변환 시작",
    exportPdf: "PDF 내보내기",
    cancel: "취소",
    exportTxt: "TXT 내보내기",
    copyText: "텍스트 복사",
    copied: (n) => `${n}자를 클립보드에 복사했습니다.`,
    exportDone: (s) => `TXT 내보내기 완료: ${s.pages}페이지, ${s.lines}줄, ${s.chars}자.`,
    txtName: "텍스트",
    pdfName: "PDF 문서",
    converted: (s) =>
      `변환 완료: <b>${s.pages_total}페이지</b>（인식 ${s.pages_ocr}페이지、건너뜀 ${s.pages_skipped}페이지）、${s.lines}줄.`,
    pdfDone: (r) => `검색 가능한 PDF 내보내기 완료: <b>${r.pages}페이지</b>.`,
    copyFailed: "복사 실패: ",
    exportFailed: "내보내기 실패: ",
    preparing: "준비 중…",
    statusPage: (p, t, phase) => `${p}/${t} 페이지 · ${phase}`,
    done: (s) =>
      `완료: <b>${s.pages_ocr}페이지</b> 인식하여 레이어 추가, ${s.pages_skipped}페이지 건너뜀, 총 ${s.lines}줄.`,
    already:
      "이 PDF는 이미 검색 가능합니다 — 모든 페이지에 자체 텍스트 레이어가 있습니다(보통 Word나 Excel에서 내보낸 경우). 인식할 픽셀이 없으므로 한 글자도 바꾸지 않고 그대로 두었습니다.",
    alreadyLog: "이 문서에는 이미 텍스트 레이어가 있어 인식이 필요 없습니다.",
    output: "출력",
    finished: "완료 ✅ 출력: ",
    cancelled: "취소되었습니다.",
    failed: "실패: ",
    statusCancelled: "취소됨",
    statusFailed: "실패",
    statusDone: "완료",
    footer: "인식은 이 컴퓨터에서만 이루어집니다. 문서는 절대 밖으로 나가지 않습니다.",
    dialogFailed: "파일 대화상자를 열 수 없습니다: ",
    saveDialogFailed: "저장 대화상자를 열 수 없습니다: ",
    notFile: "놓은 것이 파일이 아니거나 시스템이 경로를 주지 않았습니다.",
    dragNotEnabled: "드래그 앤 드롭 리스너를 사용할 수 없습니다: ",
    startLog: "처리 시작: ",
    saveDefault: "-searchable",
    themeToLight: "라이트로 전환",
    themeToDark: "다크로 전환",
    themeLabel: "테마",
    themeModeAuto: "시스템 따르기",
    themeModeLight: "라이트",
    themeModeDark: "다크",
    license: {
      title: "라이선스 인증",
      loading: "확인 중…",
      trialLeft: (d) => `무료 체험 중 — 남은 ${d}일.`,
      trialChip: (d) => `체험 · ${d}일`,
      expiredChip: "미인증",
      expired: "체험이 끝났습니다. 인식은 계속할 수 있고, PDF/TXT 내보내기에는 라이선스가 필요합니다.",
      licensed: "라이선스 등록 완료. 감사합니다.",
      licensedFamily: "라이선스 등록 완료 — 패밀리 번들. 모든 Rocktier 앱을 사용할 수 있습니다.",
      licensedNote: "이 사본은 인증되었습니다. 더 이상의 검사나 네트워크 연결은 없습니다.",
      storeNote: "이 사본은 Microsoft Store에서 구매한 것으로, 라이선스는 스토어가 관리합니다.",
      notConfigured: "이 빌드에는 검증 키가 포함되어 있지 않아 지금은 코드로 인증할 수 없습니다. hello@rocktier.com으로 문의해 주세요.",
      codeLabel: "인증 코드",
      codePlaceholder: "RKT-…",
      activate: "인증",
      activating: "인증 중…",
      buy: "구매 — $14.99",
      close: "닫기",
      invalid: "이 인증 코드는 받아들여지지 않았습니다. 입력 오류가 없는지 확인해 주세요(대소문자는 구별하지 않습니다).",
      wrongProduct: "이 인증 코드는 다른 Rocktier 앱의 것입니다. 앱마다 고유 코드가 있고, 모두를 여는 패밀리 번들도 있습니다.",
      refunded: "이 인증 코드는 환불된 구매에 묶여 있어 더 이상 사용할 수 없습니다. 잘못이라고 생각되면 주문 번호를 넣어 hello@rocktier.com으로 문의해 주세요.",
      offline: "rocktier.com에 연결할 수 없습니다. 인증에는 한 번만 네트워크가 필요하고, 그 후에는 오프라인으로 동작합니다.",
      whereToFind: "코드는 결국 직후 페이지에 표시되며, 구매 확인 이메일에도 있습니다.",
      privacyNote: "인증 시 코드가 rocktier.com에 한 번 전송되고, 서명된 응답이 로컬에 저장됩니다. 그 외에는 아무 것도 보내지 않습니다.",
      exportHintTrial: (d) => `PDF/TXT 내보내기에는 라이선스가 필요합니다 — 체험 잔여 ${d}일.`,
      exportHintExpired: "체험이 끝났습니다 — 내보내려면 먼저 인증하세요.",
    },
  },
  de: {
    title: "Rocktier OCR",
    tagline: "Scans durchsuchbar machen",
    dropBig: "PDF oder Bild hier ablegen",
    dropSub1: "Scans und reine Bild-PDFs werden erkannt und erhalten eine durchsuchbare Textebene",
    dropSub2: "Ein Bild wird in eine einseitige, durchsuchbare PDF verpackt; digital erzeugte Seiten werden unangetastet übersprungen",
    imageDone: (s) =>
      `Das Bild wurde in <b>eine einseitige, durchsuchbare PDF</b> mit ${s.lines} Textzeilen verwandelt.`,
    start: "Konvertieren",
    exportPdf: "PDF exportieren",
    cancel: "Abbrechen",
    exportTxt: "TXT exportieren",
    copyText: "Text kopieren",
    copied: (n) => `${n} Zeichen in die Zwischenablage kopiert.`,
    exportDone: (s) => `TXT exportiert: ${s.pages} Seite(n), ${s.lines} Zeilen, ${s.chars} Zeichen.`,
    txtName: "Text",
    pdfName: "PDF-Dokument",
    converted: (s) =>
      `Fertig: <b>${s.pages_total} Seite(n)</b> — ${s.pages_ocr} erkannt, ${s.pages_skipped} übersprungen, ${s.lines} Zeilen.`,
    pdfDone: (r) => `Durchsuchbare PDF exportiert: <b>${r.pages} Seite(n)</b>.`,
    copyFailed: "Kopieren fehlgeschlagen: ",
    exportFailed: "Export fehlgeschlagen: ",
    preparing: "Wird vorbereitet…",
    statusPage: (p, t, phase) => `Seite ${p}/${t} · ${phase}`,
    done: (s) =>
      `Fertig: <b>${s.pages_ocr} Seite(n)</b> erkannt und mit Textebene, ${s.pages_skipped} übersprungen, insgesamt ${s.lines} Zeilen.`,
    already:
      "Diese PDF ist bereits durchsuchbar — jede Seite trägt ihre eigene Textebene (typisch für Word-/Excel-Exporte). Es gibt keine Pixel zu erkennen, also wurde nichts verändert.",
    alreadyLog: "Das Dokument hat bereits eine Textebene; keine Erkennung nötig.",
    output: "Ausgabe",
    finished: "Fertig ✅ Ausgabe: ",
    cancelled: "Abgebrochen.",
    failed: "Fehlgeschlagen: ",
    statusCancelled: "Abgebrochen",
    statusFailed: "Fehlgeschlagen",
    statusDone: "Fertig",
    footer: "Die Erkennung läuft auf diesem Rechner. Ihr Dokument verlässt ihn nie.",
    dialogFailed: "Dateidialog ließ sich nicht öffnen: ",
    saveDialogFailed: "Speicherdialog ließ sich nicht öffnen: ",
    notFile: "Das Abgelegte war keine Datei, oder das System lieferte keinen Pfad.",
    dragNotEnabled: "Drag-and-Drop-Listener nicht verfügbar: ",
    startLog: "Verarbeitung: ",
    saveDefault: "-searchable",
    themeToLight: "Zu Hell wechseln",
    themeToDark: "Zu Dunkel wechseln",
    themeLabel: "Design",
    themeModeAuto: "System folgen",
    themeModeLight: "Hell",
    themeModeDark: "Dunkel",
    license: {
      title: "Lizenz & Aktivierung",
      loading: "Wird geprüft…",
      trialLeft: (d) => `Kostenlose Testphase — noch ${d} Tag(e).`,
      trialChip: (d) => `Test · ${d} T.`,
      expiredChip: "Nicht aktiviert",
      expired: "Die Testphase ist vorbei. Die Erkennung funktioniert weiter; das Exportieren von PDF/TXT braucht eine Lizenz.",
      licensed: "Lizenziert. Danke.",
      licensedFamily: "Lizenziert — Familiy-Bundle. Alle Rocktier-Apps sind freigeschaltet.",
      licensedNote: "Diese Kopie ist aktiviert. Keine weiteren Prüfungen, kein Netzwerkzugriff.",
      storeNote: "Diese Kopie stammt aus dem Microsoft Store; die Lizenz verwaltet der Store.",
      notConfigured: "Dieser Build trägt keinen Verifizierungsschlüssel und kann noch keinen Code aktivieren. Bitte schreiben Sie an hello@rocktier.com.",
      codeLabel: "Aktivierungscode",
      codePlaceholder: "RKT-…",
      activate: "Aktivieren",
      activating: "Wird aktiviert…",
      buy: "Kaufen — $14.99",
      close: "Schließen",
      invalid: "Dieser Code wurde nicht akzeptiert. Prüfen Sie ihn auf Tippfehler — Groß- und Kleinschreibung spielt keine Rolle.",
      wrongProduct: "Dieser Code gehört zu einer anderen Rocktier-App. Jede App hat ihren eigenen Code — oder das Familien-Bundle, das alles freischaltet.",
      refunded: "Dieser Code gehört zu einer zurückerstatteten Kauf und schaltet nichts mehr frei. Halten Sie das für einen Fehler, schreiben Sie mit Ihrer Bestellnummer an hello@rocktier.com.",
      offline: "rocktier.com war nicht erreichbar. Die Aktivierung braucht einmalig eine Verbindung; danach bleibt die App offline.",
      whereToFind: "Ihr Code erschien direkt nach dem Kauf auf der Seite und steht auch in der Kauf-E-Mail.",
      privacyNote: "Bei der Aktivierung wird der Code einmal an rocktier.com gesendet und die signierte Antwort lokal gespeichert. Nichts anderes wird übertragen.",
      exportHintTrial: (d) => `PDF/TXT-Export braucht eine Lizenz — noch ${d} Tag(e) Testphase.`,
      exportHintExpired: "Die Testphase ist vorbei — aktivieren Sie zuerst, um PDF/TXT zu exportieren.",
    },
  },
  es: {
    title: "Rocktier OCR",
    tagline: "Convierte escaneos en algo buscable",
    dropBig: "Suelta aquí un PDF o una imagen",
    dropSub1: "Los escaneos y los PDF solo-imagen se reconocen y reciben una capa de texto buscable",
    dropSub2: "Una imagen se envuelve en un PDF buscable de una página; las páginas digitales originales se saltan intactas",
    imageDone: (s) =>
      `La imagen se convirtió en <b>un PDF buscable de una página</b> con ${s.lines} líneas de texto.`,
    start: "Convertir",
    exportPdf: "Exportar PDF",
    cancel: "Cancelar",
    exportTxt: "Exportar TXT",
    copyText: "Copiar texto",
    copied: (n) => `${n} caracteres copiados al portapapeles.`,
    exportDone: (s) => `TXT exportado: ${s.pages} página(s), ${s.lines} líneas, ${s.chars} caracteres.`,
    txtName: "Texto",
    pdfName: "Documento PDF",
    converted: (s) =>
      `Conversión terminada: <b>${s.pages_total} página(s)</b> — ${s.pages_ocr} reconocidas, ${s.pages_skipped} saltadas, ${s.lines} líneas.`,
    pdfDone: (r) => `PDF buscable exportado: <b>${r.pages} página(s)</b>.`,
    copyFailed: "Error al copiar: ",
    exportFailed: "Error al exportar: ",
    preparing: "Preparando…",
    statusPage: (p, t, phase) => `Página ${p}/${t} · ${phase}`,
    done: (s) =>
      `Listo: <b>${s.pages_ocr} página(s)</b> reconocidas y con capa de texto, ${s.pages_skipped} saltadas, ${s.lines} líneas en total.`,
    already:
      "Este PDF ya es buscable: cada página trae su propia capa de texto (típico de exportaciones de Word o Excel). No hay píxeles que reconocer, así que no se cambió nada.",
    alreadyLog: "El documento ya tiene capa de texto; no hace falta reconocer.",
    output: "Salida",
    finished: "Listo ✅ salida: ",
    cancelled: "Cancelado.",
    failed: "Falló: ",
    statusCancelled: "Cancelado",
    statusFailed: "Falló",
    statusDone: "Listo",
    footer: "El reconocimiento ocurre en esta máquina. Tu documento nunca sale de ella.",
    dialogFailed: "No se pudo abrir el diálogo de archivos: ",
    saveDialogFailed: "No se pudo abrir el diálogo de guardar: ",
    notFile: "Lo soltado no era un archivo, o el sistema no dio una ruta.",
    dragNotEnabled: "El receptor de arrastrar y soltar no está disponible: ",
    startLog: "Procesando: ",
    saveDefault: "-searchable",
    themeToLight: "Cambiar a claro",
    themeToDark: "Cambiar a oscuro",
    themeLabel: "Tema",
    themeModeAuto: "Según el sistema",
    themeModeLight: "Claro",
    themeModeDark: "Oscuro",
    license: {
      title: "Licencia y activación",
      loading: "Comprobando…",
      trialLeft: (d) => `Prueba gratuita — quedan ${d} día(s).`,
      trialChip: (d) => `Prueba · ${d} d`,
      expiredChip: "Sin activar",
      expired: "Tu prueba terminó. El reconocimiento sigue funcionando; exportar PDF/TXT necesita licencia.",
      licensed: "Con licencia. Gracias.",
      licensedFamily: "Con licencia — paquete familiar. Todas las apps Rocktier desbloqueadas.",
      licensedNote: "Esta copia está activada. Sin más comprobaciones y sin acceso a la red.",
      storeNote: "Esta copia vino de la Microsoft Store; la tienda gestiona su licencia.",
      notConfigured: "Esta compilación aún no puede activar códigos: no trae clave de verificación. Escribe a hello@rocktier.com.",
      codeLabel: "Código de activación",
      codePlaceholder: "RKT-…",
      activate: "Activar",
      activating: "Activando…",
      buy: "Comprar — $14.99",
      close: "Cerrar",
      invalid: "Ese código no fue aceptado. Revisa si hay un error de tipeo — no distingue mayúsculas.",
      wrongProduct: "Ese código pertenece a otra app Rocktier. Cada app tiene el suyo — o el paquete familiar, que desbloquea todas.",
      refunded: "Ese código corresponde a una compra reembolsada y ya no desbloquea nada. Si crees que es un error, escribe a hello@rocktier.com con tu número de pedido.",
      offline: "No se pudo conectar con rocktier.com. Activar necesita una conexión; después la app queda sin red para siempre.",
      whereToFind: "Tu código apareció en la página justo tras el pago, y también está en el correo de compra.",
      privacyNote: "Activar envía el código a rocktier.com una vez y guarda la respuesta firmada en local. Nada más se transmite.",
      exportHintTrial: (d) => `Exportar PDF/TXT necesita licencia — quedan ${d} día(s) de prueba.`,
      exportHintExpired: "Tu prueba terminó — activa primero para exportar PDF/TXT.",
    },
  },
  pt: {
    title: "Rocktier OCR",
    tagline: "Torne digitalizações pesquisáveis",
    dropBig: "Arraste um PDF ou uma imagem para aqui",
    dropSub1: "Digitalizações e PDFs só de imagem são reconhecidos e recebem uma camada de texto pesquisável",
    dropSub2: "Uma imagem vira um PDF pesquisável de uma página; páginas digitais originais são ignoradas sem tocar em nada",
    imageDone: (s) =>
      `A imagem virou <b>um PDF pesquisável de uma página</b> com ${s.lines} linhas de texto.`,
    start: "Converter",
    exportPdf: "Exportar PDF",
    cancel: "Cancelar",
    exportTxt: "Exportar TXT",
    copyText: "Copiar texto",
    copied: (n) => `${n} caracteres copiados para a área de transferência.`,
    exportDone: (s) => `TXT exportado: ${s.pages} página(s), ${s.lines} linhas, ${s.chars} caracteres.`,
    txtName: "Texto",
    pdfName: "Documento PDF",
    converted: (s) =>
      `Conversão concluída: <b>${s.pages_total} página(s)</b> — ${s.pages_ocr} reconhecidas, ${s.pages_skipped} ignoradas, ${s.lines} linhas.`,
    pdfDone: (r) => `PDF pesquisável exportado: <b>${r.pages} página(s)</b>.`,
    copyFailed: "Falha ao copiar: ",
    exportFailed: "Falha ao exportar: ",
    preparing: "A preparar…",
    statusPage: (p, t, phase) => `Página ${p}/${t} · ${phase}`,
    done: (s) =>
      `Pronto: <b>${s.pages_ocr} página(s)</b> reconhecidas e com camada de texto, ${s.pages_skipped} ignoradas, ${s.lines} linhas no total.`,
    already:
      "Este PDF já é pesquisável — cada página traz a sua própria camada de texto (típico de exportações do Word ou Excel). Não há píxeis a reconhecer, por isso nada foi alterado.",
    alreadyLog: "O documento já tem camada de texto; não é preciso reconhecer.",
    output: "Saída",
    finished: "Pronto ✅ saída: ",
    cancelled: "Cancelado.",
    failed: "Falhou: ",
    statusCancelled: "Cancelado",
    statusFailed: "Falhou",
    statusDone: "Pronto",
    footer: "O reconhecimento acontece nesta máquina. O seu documento nunca sai dela.",
    dialogFailed: "Não foi possível abrir o diálogo de ficheiros: ",
    saveDialogFailed: "Não foi possível abrir o diálogo de guardar: ",
    notFile: "O que foi largado não era um ficheiro, ou o sistema não deu um caminho.",
    dragNotEnabled: "O ouvinte de arrastar e largar não está disponível: ",
    startLog: "A processar: ",
    saveDefault: "-searchable",
    themeToLight: "Mudar para claro",
    themeToDark: "Mudar para escuro",
    themeLabel: "Tema",
    themeModeAuto: "Seguir o sistema",
    themeModeLight: "Claro",
    themeModeDark: "Escuro",
    license: {
      title: "Licença e ativação",
      loading: "A verificar…",
      trialLeft: (d) => `Avaliação gratuita — faltam ${d} dia(s).`,
      trialChip: (d) => `Avaliação · ${d} d`,
      expiredChip: "Não ativado",
      expired: "A sua avaliação terminou. O reconhecimento continua a funcionar; exportar PDF/TXT precisa de licença.",
      licensed: "Licenciado. Obrigado.",
      licensedFamily: "Licenciado — pacote familiar. Todas as apps Rocktier desbloqueadas.",
      licensedNote: "Esta cópia está ativada. Sem mais verificações e sem acesso à rede.",
      storeNote: "Esta cópia veio da Microsoft Store; a loja trata da licença.",
      notConfigured: "Esta compilação ainda não consegue ativar códigos: não traz chave de verificação. Escreva para hello@rocktier.com.",
      codeLabel: "Código de ativação",
      codePlaceholder: "RKT-…",
      activate: "Ativar",
      activating: "A ativar…",
      buy: "Comprar — $14.99",
      close: "Fechar",
      invalid: "Esse código não foi aceite. Veja se há algum erro de digitação — não distingue maiúsculas.",
      wrongProduct: "Esse código pertence a outra app Rocktier. Cada app tem o seu — ou o pacote familiar, que desbloqueia todas.",
      refunded: "Esse código está ligado a uma compra reembolsada e já não desbloqueia nada. Se acredita que é um erro, escreva para hello@rocktier.com com o número do pedido.",
      offline: "Não foi possível ligar a rocktier.com. Ativar precisa de uma ligação; depois a app fica offline para sempre.",
      whereToFind: "O seu código apareceu na página logo após o pagamento, e também está no e-mail de compra.",
      privacyNote: "Ativar envia o código para rocktier.com uma vez e guarda a resposta assinada localmente. Nada mais é transmitido.",
      exportHintTrial: (d) => `Exportar PDF/TXT precisa de licença — faltam ${d} dia(s) de avaliação.`,
      exportHintExpired: "A sua avaliação terminou — ative primeiro para exportar PDF/TXT.",
    },
  },
  ar: {
    title: "Rocktier OCR",
    tagline: "اجعل الماسحات قابلة للبحث",
    dropBig: "أفلِت ملف PDF أو صورة هنا",
    dropSub1: "تُتعرَّف الماسحات وملفات PDF المصوَّرة وتُضاف إليها طبقة نص قابلة للبحث",
    dropSub2: "الصورة تُغلَّف في ملف PDF قابل للبحث من صفحة واحدة؛ أما الصفحات الرقمية الأصلية فتُترك كما هي دون حرف واحد",
    imageDone: (s) =>
      `حُوِّلت هذه الصورة إلى <b>ملف PDF قابل للبحث من صفحة واحدة</b> مع ${s.lines} سطرًا من النص.`,
    start: "ابدأ التحويل",
    exportPdf: "صدّر PDF",
    cancel: "إلغاء",
    exportTxt: "صدّر TXT",
    copyText: "انسخ النص",
    copied: (n) => `نُسِخ ${n} حرفًا إلى الحافظة.`,
    exportDone: (s) => `تم تصدير TXT: ${s.pages} صفحة، ${s.lines} سطرًا، ${s.chars} حرفًا.`,
    txtName: "نص",
    pdfName: "مستند PDF",
    converted: (s) =>
      `اكتمل التحويل: <b>${s.pages_total} صفحة</b> (تعرُّف على ${s.pages_ocr} وتخطّي ${s.pages_skipped})، ${s.lines} سطرًا.`,
    pdfDone: (r) => `تم تصدير PDF قابل للبحث: <b>${r.pages} صفحة</b>.`,
    copyFailed: "فشل النسخ: ",
    exportFailed: "فشل التصدير: ",
    preparing: "قيد التحضير…",
    statusPage: (p, t, phase) => `صفحة ${p}/${t} · ${phase}`,
    done: (s) =>
      `اكتمل: تم التعرُّف على <b>${s.pages_ocr} صفحة</b> وإضافة الطبقة، وتخطّي ${s.pages_skipped} صفحة، بإجمالي ${s.lines} سطرًا.`,
    already:
      "ملف PDF هذا قابل للبحث أصلًا — كل صفحة تحمل طبقة نصها الخاصة (وهو المعتاد في الملفات المصدَّرة من Word أو Excel). لا توجد بكسلات للتعرُّف عليها، لذا لم يُغيَّر شيء.",
    alreadyLog: "المستند يحتوي بالفعل على طبقة نص؛ لا حاجة للتعرُّف.",
    output: "الناتج",
    finished: "اكتمل ✅ الناتج: ",
    cancelled: "أُلغي.",
    failed: "فشل: ",
    statusCancelled: "أُلغي",
    statusFailed: "فشل",
    statusDone: "اكتمل",
    footer: "يحدث التعرُّف على هذه الآلة. مستندك لا يغادرها أبدًا.",
    dialogFailed: "تعذّر فتح مربع حوار الملفات: ",
    saveDialogFailed: "تعذّر فتح مربع حوار الحفظ: ",
    notFile: "ما أُفلت ليس ملفًا، أو أن النظام لم يعطِ مسارًا.",
    dragNotEnabled: "مستمع السحب والإفلات غير مفعَّل: ",
    startLog: "بدء المعالجة: ",
    saveDefault: "-searchable",
    themeToLight: "التبديل إلى الفاتح",
    themeToDark: "التبديل إلى الداكن",
    themeLabel: "السمة",
    themeModeAuto: "حسب النظام",
    themeModeLight: "فاتح",
    themeModeDark: "داكن",
    license: {
      title: "الترخيص والتنشيط",
      loading: "جارٍ التحقق…",
      trialLeft: (d) => `تجربة مجانية — تبقى ${d} يومًا.`,
      trialChip: (d) => `تجربة · ${d} يوم`,
      expiredChip: "غير منشَّط",
      expired: "انتهت التجربة. التعرُّف لا يزال يعمل؛ أما تصدير PDF/TXT فيحتاج ترخيصًا.",
      licensed: "مرخَّص. شكرًا لك.",
      licensedFamily: "مرخَّص — حزمة العائلة. جميع تطبيقات Rocktier مفتوحة.",
      licensedNote: "هذه النسخة منشَّطة. لا فحوصات إضافية ولا اتصال بالشبكة.",
      storeNote: "هذه النسخة من متجر Microsoft، والمتجر هو من يدير ترخيصها.",
      notConfigured: "هذه النسخة لا تحمل مفتاح التحقق بعد، لذا لا يمكنها تنشيط الرموز الآن. راسلنا على hello@rocktier.com.",
      codeLabel: "رمز التنشيط",
      codePlaceholder: "RKT-…",
      activate: "تنشيط",
      activating: "جارٍ التنشيط…",
      buy: "شراء — $14.99",
      close: "إغلاق",
      invalid: "لم يُقبَل هذا الرمز. تحقق من خطأ الإدخال — الأحرف الكبيرة والصغيرة لا تُفرَّق.",
      wrongProduct: "هذا الرمز يخص تطبيق Rocktier آخر. لكل تطبيق رمزه الخاص — أو حزمة العائلة التي تفتح كلها.",
      refunded: "هذا الرمز مرتبط بعملية استُردّ ثمنها، لذا لم يعد يفتح شيئًا. إن رأيت أن هذا خطأ، راسل hello@rocktier.com مع رقم طلبك.",
      offline: "تعذّر الوصول إلى rocktier.com. يحتاج التنشيط إلى اتصال واحد، وبعدها يعمل التطبيق دون شبكة.",
      whereToFind: "ظهر رمزك على الصفحة مباشرة بعد الدفع، وهو موجود أيضًا في بريد الشراء.",
      privacyNote: "يُرسَل الرمز إلى rocktier.com مرة واحدة عند التنشيط، وتُحفَظ الاستجابة الموقَّعة محليًا. لا يُرسَل أي شيء آخر.",
      exportHintTrial: (d) => `تصدير PDF/TXT يحتاج ترخيصًا — تبقى ${d} يومًا من تجربتك.`,
      exportHintExpired: "انتهت تجربتك — نشِّط أولًا لتصدير PDF/TXT.",
    },
  },
};

/* 2026-10-04 键改名 → "rocktier.lang"，与 MD / Write 同名同形。
 * 语言是用户感知最强的偏好，重置一次就等于「中文用户变英文界面」，故读取处回落旧键。 */
const LANG_KEY = "rocktier.lang";
const LANG_KEY_LEGACY = "rocktier-ocr-lang";
// 家族语言标准（随 Pic2WebP）：8 语循环切换；无保存偏好时默认英文，不嗅探系统语言。
const LANG_ORDER = ["en", "zh", "ja", "ko", "de", "es", "pt", "ar"];
const LANG_NAMES = {
  en: "EN", zh: "中文", ja: "日本語", ko: "한국어",
  de: "Deutsch", es: "Español", pt: "Português", ar: "العربية",
};
const _savedLang = localStorage.getItem(LANG_KEY) ?? localStorage.getItem(LANG_KEY_LEGACY);
let current = LANG_ORDER.includes(_savedLang) ? _savedLang : "en";

function tr() {
  return STRINGS[current] || STRINGS.en;
}

function applyLang() {
  const t = tr();
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (t[key] !== undefined) node.innerHTML = t[key];
  });
  // 无障碍底线：屏幕阅读器要用对应语言的语音引擎；阿语连带翻转书写方向
  document.documentElement.lang = current;
  document.documentElement.dir = current === "ar" ? "rtl" : "ltr";
  const toggle = document.getElementById("rocktier.lang");
  if (toggle) {
    const next = LANG_ORDER[(LANG_ORDER.indexOf(current) + 1) % LANG_ORDER.length];
    toggle.textContent = LANG_NAMES[next];
    toggle.title = current === "ar" ? "" : LANG_NAMES[current];
  }
  localStorage.setItem(LANG_KEY, current);
}

function toggleLang() {
  current = LANG_ORDER[(LANG_ORDER.indexOf(current) + 1) % LANG_ORDER.length];
  applyLang();
}

document.addEventListener("DOMContentLoaded", () => {
  applyLang();
  const toggle = document.getElementById("rocktier.lang");
  if (toggle) toggle.addEventListener("click", toggleLang);
});
